services:
  doordash-drive:
    build:
      context: ./
    command: uvicorn fast_api_server.main:app --host 0.0.0.0 
    networks:
      - mynet
    ports:
      - 8099:8000
  doordash-drive-mcp:
    build:
      context: ./
    command: uvicorn fast_api_server.main:app --host 0.0.0.0 
    networks:
      - mynet
    ports:
      - 8199:8000
    depends_on:
      - doordash-drive
networks:
  mynet:
    driver: bridge