services:
  doordash-drive:
    build:
      context: ./
    command: uvicorn fast_api_server.main:app --host 0.0.0.0 
    networks:
      - mynet
    ports:
      - 8099:8000
    depends_on:
      - postgresql
  doordash-drive-mcp:
    build:
      context: ./
    command: python -m fast_mcp_server.main
    networks:
      - mynet
    ports:
      - 8199:8000
    depends_on:
      - doordash-drive
  postgresql:
    image: postgres:14.20-alpine3.23
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - mynet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: doordash
      POSTGRES_DB: doordash

  adminer:
    image: adminer
    restart: always
    networks:
      - mynet
    ports:
      - 8011:8080
    depends_on:
      - postgresql

volumes:
  postgres-data:
    name: postgres-data
networks:
  mynet:
    driver: bridge